### PR TITLE
misc fixes

### LINKED ISSUE #2129: Integrations Help Page
Add an integrations help page. Describe how to use the tab.

- [x] How to configure integrations (API keys)
- [x] How to disable integrations (don't show up on the main page)
- [x] How to navigate to the home page
- [x] Can search integrations
- [x] Integrations are configured per user, not per Cont3xt application

### PR DESCRIPTION
**Pull request by 31453**
update browserlist
fix button color/position of create raw edit link groups update viewer help
update cont3xt help fixes #2129
fix integrations search

### CODE REVIEW

File: cont3xt/vueapp/src/components/pages/Help.vue [hunk 1]
```diff
@@ -93,11 +93,29 @@
...
-          </b-card>
-        </div>
+        <h3>
+          <span class="fa fa-fw fa-key mr-2"></span>
+          Integrations
+        </h3>
+        <p>
+          You must use this page to configure your integations.
+          Most integrations require API keys (and some require more data) in order to use them.
+          Integrations are configured per user, not per Cont3xt application.
```
Comment (awick) [inline cont3xt/vueapp/src/components/pages/Help.vue:103]: you can do global config in the config file and then we show a globe. this will over ride it. we should mention that

File: package-lock.json [hunk 2]
```diff
@@ -5560,6 +5560,10 @@
         {
           "type": "tidelift",
           "url": "https://tidelift.com/funding/github/npm/caniuse-lite"
+        },
+        {
+          "type": "github",
+          "url": "https://github.com/sponsors/ai"
```
Comment (awick) [inline package-lock.json:5566]: what dis?

**Review by awick — APPROVED** [review]
